---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1-stage-app
  labels:
    app: project-1-stage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-1-stage-app
  template:
    metadata:
      labels:
        app: project-1-stage-app
      annotations:
        vault.security.banzaicloud.io/enable-json-log: "true"
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault/"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-role: "project-1__stage"
        vault.security.banzaicloud.io/transit-path: "project-1/transit"
        vault.security.banzaicloud.io/transit-key-id: "stage"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        # Fail if at least one secret is unavailable (be cause of encrypted secret that can not be decrypted with wrong key)
        vault.security.banzaicloud.io/vault-ignore-missing-secrets: "true"
        vault.security.banzaicloud.io/vault-env-daemon: "true"
    spec:
      containers:
        - name: stage-app
          image: yuriiashutkin/web-app:1.2.1-scratch
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PLAIN_ENV
              value: stored-in-git
            - name: FROM_VAULT_TOKEN_V1
              value: "vault:project-1/kv/data/stage/token#value#1"
            - name: FROM_VAULT_TOKEN_V2
              value: "vault:project-1/kv/data/stage/token#value#2"
            # TODO: this value should be actual for every installation
            - name: FROM_VAULT_ENCRYPTED
              value: "vault:v1:psajosIWWS9fRU1prKO3fQ6qgAmEiVh57rUWMB7el1+MqBMl5mpacAW61j6wyw=="
            - name: FROM_VAULT_DB_URL
              value: "postgres://${vault:project-1/database/creds/dev-setup__stage__project_ro#username}:${vault:project-1/database/creds/dev-setup__stage__project_ro#username#password}@project-1-pgsql.dev-setup:5432/project_db?search_path=public&sslmode=disable"
            - name: SECRETS_DIRS
              value: "/etc/db-creds"
          volumeMounts:
            - name: db-creds
              mountPath: "/etc/db-creds"
              readOnly: true
      volumes:
        - name: db-creds
          secret:
            secretName: db-creds
            defaultMode: 0404
