---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1-pgsql
  labels:
    app: project-1-pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-1-pgsql
  template:
    metadata:
      labels:
        app: project-1-pgsql
      annotations:
        vault.security.banzaicloud.io/enable-json-log: "true"
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault/"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-role: "project-1__pgsql"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        # Fail if at least one secret is unavailable (be cause of encrypted secret that can not be decrypted with wrong key)
        vault.security.banzaicloud.io/vault-ignore-missing-secrets: "false"
    spec:
      serviceAccountName: project-1-pgsql
      automountServiceAccountToken: true
      containers:
        - name: project-1-pgsql
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: "vault:project-1/kv/data/dev/db_creds#db_pass#1"
            - name: POSTGRES_USER
              value: "vault:project-1/kv/data/dev/db_creds#db_user#1"
            - name: POSTGRES_DB
              value: "vault:project-1/kv/data/dev/db_creds#db_name#1"
          volumeMounts:
            - name: project-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: project-db-init
          configMap:
            name: project-db-init-script

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-db-init-script
data:
  project_db-init.sql: |
    CREATE TABLE clients
    (
        uid         integer CONSTRAINT no_null NOT NULL,
        name        TEXT COLLATE "C" NOT NULL,
        surname     TEXT COLLATE "C"
    );
    INSERT INTO clients VALUES (1, 'John', 'Smith');
    INSERT INTO clients VALUES (2, 'Lilian', 'Worksmith');
    INSERT INTO clients VALUES (3, 'Michael', 'Rupert');
