---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.7.6
          ports:
            - containerPort: 8200
              protocol: TCP
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "12345"
