---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  db_user: d2ViLWFwcA==
  db_pass: T2I1Z3VxdTllZU1pZWdob3NoNm8=
  db_host: ZGF0YWJhc2UubG9jYWw=
  db_name: d2ViLWFwcF9kYg==
